#ifndef UEBHYDROCOUPLECOMPONENT_GLOBAL_H
#define UEBHYDROCOUPLECOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef UEBHYDROCOUPLECOMPONENT_LIB
# define UEBHYDROCOUPLECOMPONENT_EXPORT Q_DECL_EXPORT
#else
# define UEBHYDROCOUPLECOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // UEBHYDROCOUPLECOMPONENT_GLOBAL_H
